#!/usr/bin/env tsx
/**
 * Build-time codegen: read T3's canonical USDC EIP-712 domain artefact
 * (`contracts/scripts/arc-testnet-usdc-domain.json`) and emit a TypeScript
 * module under `src/generated/` that exports the same values as a const.
 *
 * Why: networks.ts previously did `readFileSync(...../contracts/scripts/...)`
 * at module load. That works inside the monorepo (relative path resolves) but
 * crashes after `npm install` because the published `dist/` lives under
 * `node_modules/@universal-paywall/middleware/` with no `contracts/` sibling.
 *
 * This generator preserves the single source of truth (the JSON file owned by
 * Task 3) while making the values part of the published bundle.
 *
 * Idempotent: re-running with no JSON change is a no-op write.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(here, '../../..');
const JSON_PATH = resolve(REPO_ROOT, 'contracts/scripts/arc-testnet-usdc-domain.json');
const OUT_DIR = resolve(here, '../src/generated');
const OUT_PATH = resolve(OUT_DIR, 'arc-testnet-usdc-domain.ts');

interface ArcTestnetUsdcDomain {
  name: string;
  version: string;
  decimals: number;
  supportsEip3009: boolean;
  sampleGasCost?: string;
  gasCostExceedsThreshold?: boolean;
  notes?: string[];
}

function main(): void {
  if (!existsSync(JSON_PATH)) {
    throw new Error(
      `T3 USDC domain artefact missing at ${JSON_PATH} — run T3 first (or this script before publish).`,
    );
  }

  const parsed = JSON.parse(readFileSync(JSON_PATH, 'utf8')) as ArcTestnetUsdcDomain;
  if (typeof parsed.name !== 'string' || typeof parsed.version !== 'string') {
    throw new Error(
      `T3 USDC domain artefact at ${JSON_PATH} is missing required fields (name, version).`,
    );
  }
  if (typeof parsed.decimals !== 'number' || !Number.isInteger(parsed.decimals)) {
    throw new Error(
      `T3 USDC domain artefact at ${JSON_PATH} has invalid decimals (expected integer, got ${typeof parsed.decimals}).`,
    );
  }
  if (typeof parsed.supportsEip3009 !== 'boolean') {
    throw new Error(
      `T3 USDC domain artefact at ${JSON_PATH} has invalid supportsEip3009 (expected boolean, got ${typeof parsed.supportsEip3009}).`,
    );
  }
  if (parsed.sampleGasCost !== undefined && typeof parsed.sampleGasCost !== 'string') {
    throw new Error(
      `T3 USDC domain artefact at ${JSON_PATH} has invalid sampleGasCost (expected string or absent).`,
    );
  }
  if (
    parsed.gasCostExceedsThreshold !== undefined &&
    typeof parsed.gasCostExceedsThreshold !== 'boolean'
  ) {
    throw new Error(
      `T3 USDC domain artefact at ${JSON_PATH} has invalid gasCostExceedsThreshold (expected boolean or absent).`,
    );
  }

  const emitted = {
    name: parsed.name,
    version: parsed.version,
    decimals: parsed.decimals,
    supportsEip3009: parsed.supportsEip3009,
    sampleGasCost: parsed.sampleGasCost ?? null,
    gasCostExceedsThreshold: parsed.gasCostExceedsThreshold ?? false,
    notes: Array.isArray(parsed.notes) ? parsed.notes : [],
  };

  const body = [
    '// AUTO-GENERATED by scripts/generate-arc-testnet-usdc-domain.ts.',
    '// Source of truth: contracts/scripts/arc-testnet-usdc-domain.json (Task 3).',
    '// Do not edit by hand; re-run `npm run build` (which triggers prebuild) to refresh.',
    '',
    'export interface ArcTestnetUsdcDomain {',
    '  name: string;',
    '  version: string;',
    '  decimals: number;',
    '  supportsEip3009: boolean;',
    '  sampleGasCost: string | null;',
    '  gasCostExceedsThreshold: boolean;',
    '  notes: string[];',
    '}',
    '',
    `export const arcTestnetUsdcDomain: ArcTestnetUsdcDomain = ${JSON.stringify(emitted, null, 2)} as const;`,
    '',
  ].join('\n');

  if (!existsSync(OUT_DIR)) {
    mkdirSync(OUT_DIR, { recursive: true });
  }

  let prev = '';
  if (existsSync(OUT_PATH)) {
    prev = readFileSync(OUT_PATH, 'utf8');
  }
  if (prev !== body) {
    writeFileSync(OUT_PATH, body);
    process.stdout.write(`wrote ${OUT_PATH}\n`);
  } else {
    process.stdout.write(`up to date: ${OUT_PATH}\n`);
  }
}

try {
  main();
} catch (err) {
  process.stderr.write(`generate-arc-testnet-usdc-domain: ${(err as Error).message}\n`);
  process.exit(1);
}
